# Generated by Django 5.0.6 on 2024-06-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userbirthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nationnality', models.CharField(max_length=100)),
                ('birthday', models.DateField(max_length=100)),
            ],
        ),
    ]
