# Generated by Django 5.0.6 on 2024-06-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userbirthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='contacter name')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='email')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='topic')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='detail')),
            ],
        ),
    ]
