# Generated by Django 5.0.6 on 2024-06-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='detail_answer',
            field=models.TextField(blank=True, null=True, verbose_name='detailed answer'),
        ),
    ]
