# Generated by Django 5.0.6 on 2024-06-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_consultation_detail_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='contacter name'),
        ),
    ]
