# Generated by Django 5.0.6 on 2024-06-18 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_category_model_product_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_model',
            old_name='unite',
            new_name='unit',
        ),
    ]
