# Generated by Django 5.0.6 on 2024-06-20 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_profile_model_tel_discount_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount_model',
        ),
    ]
