# Generated by Django 5.0.6 on 2024-06-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_product_model_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_model',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
